sonar.projectKey=make-u-move-raw_CILAOS
sonar.organization=make-u-move-raw


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Cilaos
sonar.projectVersion=0.1


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.language=cpp
sonar.exclusions=tests/**

# Might be useful for advanced code after
# sonar.cfamily.build-wrapper-output=bw-output
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
