name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t cilaos .

    - name: Build app
      run: docker run --rm -v build-volume:/app/build cilaos ./run.sh build

    - name: Run tests
      run: docker run --rm -v build-volume:/app/build cilaos ./run.sh test-only


    - name: Generate doc
      run: docker run --rm cilaos ./run.sh doc