name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR # TODO: Remove logging with PAT once package will be set to public
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build project in docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/agheroo/cilaos:latest
          options: --rm
        run: |
          chmod +x run.sh
          ./run.sh build-only

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR for docker # TODO: Remove logging with PAT once package will be set to public
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run tests with docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/agheroo/cilaos:latest
          options: --rm
        run: ./run.sh test-only

  doc:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/<ton-username>/monprojet:latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR for docker # TODO: Remove logging with PAT once package will be set to public
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run tests with docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/agheroo/cilaos:latest
          options: --rm
      - name: Generate documentation
        run: ./docker_run.sh doc